server:
  port: 8189
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
